### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by standayweb** [KyleAMathews/react-markdown-textarea#13]
Seeing a weird issue on react markdown textarea, great component by the way! Not sure exactly what is causing it but as my article editor is in a modal it causes the modal to close. Maybe it is the textarea autosize, any idea how to fix? https://www.youtube.com/watch?v=b6TfERJLzYw

**Comment by KyleAMathews** [comment]
I'm guessing this doesn't have anything to do with this component. Perhaps there's another click handler in your app that's causing the re-render / modal close? In any case, it'll be really hard for me to debug from here. I'll close this but if you do find this component to be at fault in some way, feel free to submit a PR to fix it.
